"""add deadline_text to scholarship

Revision ID: f2252695ac00
Revises: 309890b85896
Create Date: 2025-08-26 11:51:39.191649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f2252695ac00'
down_revision: Union[str, Sequence[str], None] = '885b7ec19ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship', sa.Column('deadline_text', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarship', 'deadline_text')
    # ### end Alembic commands ###
